file_format: "1"
id: holyiot_nrf52840
name: holyiot_nrf52840
type: board
arch: arm
url: https://github.com/eviallet/zmk-config
features:
  - keys
  # - trackball
outputs:
  - usb
  - ble
exposes: [holyiot_connector]