identifier: holyiot_nrf52840
name: Holyiot nRF52840
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - ble
  - counter
  - gpio
  - kscan
  - i2c
  - ieee802154
  - nvs
  - usb_cdc
  - usb_device
  - watchdog
